# Generated by Django 5.1 on 2024-08-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="summary",
        ),
    ]
